---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: poc-app
  template:
    metadata:
      labels:
        app: poc-app
    spec:
      containers:
      - name: poc
        image: m1devopspoc.azurecr.io/sre-m1-poc:v1
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: acr-registry
    
---
apiVersion: v1
kind: Service
metadata:
  name: poc-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: poc-app
