package com.learn.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.util.UUID;

/**
 * Created by rishi.khurana on 10/10/2018.
 */
@DynamoDBTable(tableName = "eqs-user")
public class User {

    @DynamoDBHashKey(attributeName = "Id")
    @DynamoDBAutoGeneratedKey
    private UUID id;
    private String email;
    private String password;
    private String name;
    private String username;
    private String roleid;

    public User() {}

    //Copy constructor
    public User(User user) {
        this.setEmail(user.getEmail());
        this.setId(user.getId());
        this.setName(user.getName());
        this.setUsername(user.getUsername());
        this.setRoleid(user.getRoleid());
        this.setPassword(user.getPassword());
    }

    public User(String email, String password, String name, String username, String roleid) {
        this.email = email;
        this.password = password;
        this.name = name;
        this.username = username;
        this.roleid = roleid;
    }

    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getRoleid() {
        return roleid;
    }

    public void setRoleid(String roleid) {
        this.roleid = roleid;
    }
}
